version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_DB_URL=${SUPABASE_DB_URL}
      - JWT_SECRET=seu_secret_muito_seguro
      - JWT_EXPIRES_IN=24h
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "node src/database/migrate.js && npm install && npm run start"
