CREATE TABLE IF NOT EXISTS custoobra (
    id SERIAL PRIMARY KEY,
    valor DECIMAL(10,2) NOT NULL,
    obra VARCHAR(255) NOT NULL,
    duracao DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 